### ISSUE TITLE
Add Mercenaries

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#110]

**Comment by wspencermiller** [comment]
Looking into this. Since we can add allies already, and they're not restricted per the GHB, what should the structure be? I can add the "Mercenary Companies" as a separate army, but am hesitant to have it import _all_ of the available units just to get the special abilities. 

I'm thinking of just adding the companies as units themselves:

Army: Mercenary Companies
Unit: Greyfyrd Mercenary Company
- Ability
Unit: Etc.
- Ability

**Comment by thundergore** [comment]
I like to think that users won't need to know whats restricted by using this tool, they'll be using other tools to do that (warscroll builder, physical/digital books). So in that sense I have no problem with a user adding Grefyrd (for example) and then adding a Runefather. It might be akin to a user adding a realm when they're going to a tourney that forbids realms.

**Comment by wspencermiller** [comment]
I think that's a fair ask for now. It can always be revised in the future ‾\_(ツ)_/‾
