### ISSUE TITLE
Slaanesh Outdated Rules

### ISSUE THREAD

**Issue by Whampo0** [daviseford/aos-reminders#1255]
**Name of the rule:**
The whole thing
**Correct Rule Text:**
Totally different
> During your hero phase... etc
The whole thing
![Screenshot 2021-04-17 010544](https://user-images.githubusercontent.com/82700589/115106344-1d546100-9f19-11eb-8c7a-985e32b4cddf.jpg)

**Comment by exonian** [comment]
Hi there

We do seem to have the old Locus rule in there, which I think slipped through because it was already there but needed changing.

However, all of the things in your screenshot [have been added](https://github.com/daviseford/aos-reminders/pull/1226)

Looking at version release dates, I suspect the bottom of your page will say v.4.0.2, and we're on v4.0.3 now.

If you make sure all tabs of aosr are closed, and then open a new tab and give it a moment, hopefully you'll get a banner prompting you to reload.
Alternatively, you could try on another device or browser, or in an incognito / private window.

If you continue to have issues with it, I'd recommend trying to log out and log back in, and then if you still have no luck post here or in our discord.

![aosr_slaanesh](https://user-images.githubusercontent.com/1237986/115106706-359a9f00-9f5e-11eb-9daa-6ba9114728cb.png)

**Comment by Whampo0** [comment]
Awesome, sorry you were 100% right. Thanks.
The only other issue I had was Bladebringer on seeker chariot is worded differently and doesn't import automatically from Battlescribe.
![image](https://user-images.githubusercontent.com/82700589/115120735-db9cd800-9f63-11eb-8c6c-44a644d8ecbd.png)

**Comment by exonian** [comment]
OK great, we'll make sure to add that to our list of those to help the importer, thanks
