### ISSUE TITLE
Add meaningful tests to the project

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#135]

**Comment by thundergore** [comment]
Given we're working on a hobby project, we're talking about testing that's least effort with decent results. 

I don't know much automation - so there's time involved to learn to set that up (but, like with git, it's a good learning project for me). 

Then, on the other hand, manual testing might not be practical (depending on the range of test cases) because I'm sure many are  doing this for fun (and it eats into painting time :P)

Maybe work on the test cases to begin with?

**Comment by daviseford** [comment]
Once I implement spells, I think I will want some basic testing of our reducers and stuff. Typescript takes care of a lot of things for us already, so I'm not too worried about this for now, just wanted to make a note for down the line.

**Comment by daviseford** [comment]
I added some nice tests with PR #184 :) It's a start!
