### ISSUE TITLE
Add Swifthawk Agents

### ISSUE THREAD

**Issue by daviseford** [daviseford/aos-reminders#992]
I'm seeing Warscroll PDF's with Faction === `Swifthawk Agents` being imported.

Are these CoS imports? If so, we need data entry for their units - such as Spireguard, Reavers, etc

I will add some commented-out tests that we can get started with

**Comment by exonian** [comment]
As far as I know, they're an Order keyword without allegiance abilities. Pretty sure they're not part of Cities of Sigmar. They have points, and you technically could run them as allegiance Swifthawk Agents but I don't know why you would ever do that instead of running them as mixed Order. We should have their units though, yeah.

**Comment by daviseford** [comment]
So should they just be classified as an `ORDER` faction? Nothing more specific?

**Comment by exonian** [comment]
Yeah I think so.
